services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_pass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
